steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveusgcp/cloud-commentend,'tag:comment', '.', ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveusgcp/cloud-commentend']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','cloud-commentend', '--image', 'gcr.io/niveusgcp/cloud-commentend:${SHORT_SHA}', '--region', 'us-central1', '--quiet']
